# Generated by Django 5.2.6 on 2025-10-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.IntegerField(help_text='Duración en años')),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='myapp.carrera'),
        ),
    ]
